title: YEETUS
author: Bobby Munchkins
email: LeeJitgui@realmail.co.uk
description: > # this means to ignore newlines until "baseurl:"
  I'm...
      L E A R N I N G

# social links
twitter_username: River_OTR # DO NOT include the @ character, or else the build will fail!
github_username:  MRS-Joe # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
